version: '3'

services:
  rooster_app:
    build:
      context: .
    ports: 
      - '8080:8080'
    environment:
      - ROSTAR_USER=${ROSTAR_USER}
      - ROSTAR_PASS=${ROSTAR_PASS}
    volumes:
      - ./data:/data